title: "Steve Jobs – Bilingual Biography"
description: "Arabic & English biography with Apple-style dark glass theme"
theme: minima

# Set these so links/meta resolve correctly:
url: "https://hossamtabana.github.io"
baseurl: "/steve-jobs-bio"

lang: en

sass:
  sass_dir: assets    # LOOK: we compile from /assets
  style: compressed

minima:
  skin: classic

plugins:
  - jekyll-feed
